<!-- EXPERIENCE  -->
<section class="chiffre-cle reveal" >
	<div class="chiffre-cle-box">
		<ul>
			<div class="li-border"><li><span>+ de 15 ans</span><span class="chiffre-cle-info">d'expérience</span></li></div>
			<div class="li-border"><li><span>+ de  20</span><span class="chiffre-cle-info">collaborateurs</span></li></div>
			<div class="li-border"><li><span>+ de 1000</span><span class="chiffre-cle-info">clients</span></li></div>
			<div class="li-border"><li><span>+ de 1000</span><span class="chiffre-cle-info">programmes immobiliers</span></li></div>
			<div class="li-border"><li><span>+ de 3000</span><span class="chiffre-cle-info">supports financiers</span></li></div>
		</ul>
	</div>
</section>


<!-- ABOUT  -->
<section class="bg-blue" id="about">
	<div class="about-txt reveal">
		<p class="text-bigger text-right reveal">Qui sommes-nous ?</p>
		<p class="text-right reveal">Face à un environnement juridique et fiscal, complexe Adrien Boucher, Arthur Geidel et Arthur Raffin décident d'ouvrir un cabinet de gestion de patrimoine avec une réelle expertise. C'est grâce à une éthique et des exigences similaires que les trois amis ont décidés de commencer une nouvelle aventure ensemble. Aujourd'hui, notre cabinet a pour but de guider et d'accompagner une clientèle de particuliers et de professionnels dans le développement et la consolidation de leur patrimoine. Se sentir accompagné par Dynasty Patrimoine aura un tout autre goût avec à notre approche innovante et notre suivi sur-mesure appréciable.</p>
	</div>
</section>
