<!-- Footer -->
<footer>
	<section>
		<p class="info-wv reveal"></p>
		<nav>
			<ul class="nav-footer reveal"> 
				<li><a class ="li-links" href="#homepage">Accueil</a></li>
				<li><a class ="li-links" href="#about">Qui sommes nous ?</a></li>
				<li><a class ="li-links" href="#services-container">Nos domaines d’expertise</a></li>
				<li><a class ="li-links" href="#partenariats">Nos partenaires</a></li>
				<li><a class ="li-links" href="#contact">Contact</a></li>
				<li><a href="index.php?page=mentions">Mentions légales</a></li>
			</ul>
		</nav>
		<p class="clr reveal" style="text-align:center">Dynasty Patrimoine - Copyright 2022 Tous droits réservés </p>
	</section>
	
</footer>
