<!DOCTYPE html>
<html lang="fr">
	<head>
    <!-- SEO -->
		<meta charset="utf-8"/>
    <meta name="description" content=""/>
    <meta name="robots" content="index,follow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="patrimoine">
    <title>Conseil en gestion de patrimoine</title>
    <!-- CSS  -->
    <link rel="icon" type="images/vg" sizes="16x16" href="img/favicon.png">
    <link rel="stylesheet" type="text/css" href="css/style.css">
  </head>
  
  <body>
    <main>
      <?php require $page ?>
    </main>
      
    <!-- Scripts -->
    <script defer src="./js/api.js" ></script>
    <script defer src="./js/script.js"></script>

    <!-- READ MORE  -->
    <!-- <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script> -->

  </body>
</html>

<!-- ©Copyright Aïna LAGRANDE  -->