<!-- MENU  -->
<article class="nav_bars">
	<div class="menu-accueil">
		<!-- NAVBAR -->
		<nav id="barre-menu" class="nav-bar">
			<div class="logo-menu"><a href="index.php?page=homepage"><img src="img/logo-rem.png" alt="logo de Dynasty Patrimoine"></a></div>
			<ul class="menu">
				<li><a class ="li-links" href="#about">Qui sommes nous<span class="menu-line"></span></a></li>
				<li><a class ="li-links" href="#services">Nos domaines d'expertise<span class="menu-line"></span></a></li>
				<li><a class ="li-links" href="#partenariats">Nos partenaires<span class="menu-line"></span></a></li>
				<li><a class ="li-links" href="#contact">Contact<span class="menu-line"></span></a></li>
			</ul>
		</nav>
	</div>

	<div id="burger-menu" onclick="navBarMobilFunction()">
	<span></span>
	</div>

	<div id="menu">
		<ul>
			<li><a class ="li-links" href="#about">Qui sommes nous<span class="menu-line"></span></a></li>
			<li><a class ="li-links" href="#services">Nos domaines d'expertise<span class="menu-line"></span></a></li>
			<li><a class ="li-links" href="#partenariats">Nos partenaires<span class="menu-line"></span></a></li>
			<li><a class ="li-links" href="#contact">Contact<span class="menu-line"></span></a></li>
		</ul>
</div>

</article>
