<!-- PARTENAIRES  -->
<section class="bg-gray" id="partenariats">
	<h2 class="line reveal"><span>Plus de 200 Partenaires...</span></h2>
	<p style="text-align:center;" class="reveal partners partenaires_descktop reveal"><img src="img/partenaires2.png" alt="Nos partenaires" style="width:100%;max-width:1300px;"></p>
	<p style="text-align:center;" class="reveal partners partenaires_mobil reveal"><img src="img/partenaires_mobil2.png" alt="Nos partenaires" style="width:100%;max-width:1300px;"></p>
</section>