<h2 class="line services_line reveal" id="services"><span>Nos domaines d'expertise</span></h2>
  <div class="container"> 
    <!-- CARD 1  -->
    <div class="card_box">
      <div class="card reveal">
        <div class="icon">
          <img src="img/svg/head.svg" alt="logo de salutation" class="services-logo">
          <h3>L'immobilier d'invesstissement</h3>
        </div>
        <div class="content">
          <p>Le pôle « immobilier d’investissement » regroupe les mécaniques d’ingénierie immobilière :</p> 
          <ul>
            <li>- Défiscalisation immobilière (réduction d’impôts, déduction d’impôts)</li>
            <li>- La location meublée (LMNP/LMP)</li>
            <li>- Le démembrement (nue-propriété / usufruit)</li>
            <li>- L’immobilier institutionnel (voir SCPI)</li>
          </ul>
        </div>
        <!-- <div class=" more button__holder">
          <button class="plus"></button>
        </div> -->
      </div>

      <!-- CARD 2 -->
      <div class="card reveal">
        <div class="icon">
          <img src="img/svg/bloc.svg" alt="logo de salutation" class="services-logo">
          <h3>Les Placements Financiers</h3>
        </div>
        <div class="content">
          <p>Dynasty Patrimoine, cabinet de conseil en gestion de patrimoine indépendant, a accès aux meilleurs outils d’analyse et de suivi des marchés financiers ainsi qu’aux principaux supports de placements disponibles, lui permettant de construire une allocation d’actifs performante, objective et tournée vers les intérêts du client :</p> 
          <ul>
            <li>- Contrats d’assurance-vie</li>
            <li>- Contrats de Capitalisation</li>
            <li>- Contrats luxembourgeois</li>
            <li>- PEA, comptes titres</li>
          </ul>
        </div>
        <!-- <div class=" more button__holder">
          <button class="plus"></button>
        </div> -->
      </div>

      <!-- CARD 3 -->
      <div class="card reveal">
        <div class="icon">
          <img src="img/svg/clock.svg" alt="logo de salutation" class="services-logo">
          <h3>La Fiscalité</h3>
        </div>
        <div class="content">
          <p>Le pôle de compétence « fiscalité » de Dynasty Patrimoine vous permet d’optimiser votre fiscalité en utilisant les différentes lois et mesures en vigueur :</p> 
          <ul>
            <li>- Optimisation fiscale</li>
            <li>- Impôt sur le revenu</li>
            <li>- Impôt sur les sociétés</li>
            <li>- Contributions sociales</li>
            <li>- ISF</li>
          </ul>
        </div>
        <!-- <div class=" more button__holder">
          <button class="plus"></button>
        </div> -->
      </div>
    </div>

    <div class="card_box">
      <!-- CARD 4  -->
      <div class="card reveal">
        <div class="icon">
          <img src="img/svg/gear.svg" alt="logo de salutation" class="services-logo">
          <h3>Les SCPI</h3>
        </div>
        <div class="content">
          <p>Le pôle « immobilier institutionnel » vous donne accès à l’ensemble de toutes les SCPI de rendement du marché. Dynasty Patrimoine  vous aidera à construire la meilleure allocation en fonction de vos sensibilités :</p> 
          <ul>
            <li>- SCPI de bureaux</li>
            <li>- SCPI de santé ou d’éduction</li>
            <li>- SCPI européenne</li>
            <li>- SCPI de commerces/murs de magasins</li>
            <li>- SCPI de e-commerce</li>
            <li>- SCPI d’habitation</li>
          </ul>
        </div>
        <!-- <div class=" more button__holder">
          <button class="plus"></button>
        </div> -->
      </div>
      
      <!-- CARD 5 -->
      <div class="card reveal">
        <div class="icon">
          <img src="img/svg/lamp.svg" alt="logo de salutation" class="services-logo">
          <h3>La Retraite / Prévoyance</h3>
        </div>
        <div class="content">
          <p>Le pôle « retraite/prévoyance » vous aide à sélectionner et mettre en place la ou les meilleures solutions en matière de préparation de votre retraite.</p> 
          <ul>
            <li>- PERP/PERCO</li>
            <li>- Madelinli</li>
            <li>- Article 83</li>
          </ul>
        </div>
        <!-- <div class=" more button__holder">
          <button class="plus"></button>
        </div> -->
      </div>

      <!-- CARD 6 -->
      <div class="card reveal">
        <div class="icon">
          <img src="img/svg/not.svg" alt="logo de salutation" class="services-logo">
          <h3>La Succession / Transmission</h3>
        </div>
        <div class="content">
          <p>Vous souhaitez anticiper au mieux la transmission de votre patrimoine à vos enfants, préparer votre succession. Les experts de Dynasty Patrimoine sont à votre disposition pour vous accompagner.</p> 
        </div>
        <!-- <div class=" more button__holder">
          <button class="plus"></button>
        </div> -->
      </div>
    </div>
  </div>
