   <!-- TEAM SECTION  -->
<div class="bumper reveal" id="team-container">
   <h2 class="line"><span>Nos metiers</span></h2>
</div>

<section class="container">
    <div class="space-holder reveal">
        <div class="sticky">
            <div class="horizontal">
                <section role="feed" class="cards">
                    <article class="sample-card">
                        <img src="img/img-team1" alt=" photo de personnel">
                        <div class="team-names reveal"><h3>Marie Chollet</h3></div>
                        <div class="team-presentation reveal"><p>If you have questions or any issues regarding business law this option is for you.</p></div>
                    </article>

                    <article class="sample-card">
                        <img src="img/img-team2" alt=" photo de personnel">
                        <div class="team-names reveal"><h3>Marie Chollet</h3></div>
                        <div class="team-presentation reveal"><p>If you have questions or any issues regarding business law this option is for you.</p></div>
                    </article>

                    <article class="sample-card">
                        <img src="img/img-team3" alt=" photo de personnel">
                        <div class="team-names reveal"><h3>Marie Chollet</h3></div>
                        <div class="team-presentation reveal"><p>If you have questions or any issues regarding business law this option is for you.</p></div>
                    </article>

                    <article class="sample-card">
                        <img src="img/img-team1" alt=" photo de personnel">
                        <div class="team-names reveal"><h3>Marie Chollet</h3></div>
                        <div class="team-presentation reveal"><p>If you have questions or any issues regarding business law this option is for you.</p></div>
                    </article>
                    <article class="sample-card">
                        <img src="img/img-team2" alt=" photo de personnel">
                        <div class="team-names reveal"><h3>Marie Chollet</h3></div>
                        <div class="team-presentation reveal"><p>If you have questions or any issues regarding business law this option is for you.</p></div>
                    </article>
                </section>
            </div>
        </div>
    </div>
</section>
